# OpenAI API Configuration
[openai]
api_key = "your-openai-api-key"

# Database Configuration
[database]
url = "your-database-url"

# Authentication
[auth]
secret_key = "your-secret-key"
algorithm = "HS256"
access_token_expire_minutes = 30

# Vector Store
[vector_store]
persist_directory = "data/vector_store"

# Email Configuration (if needed)
[email]
smtp_server = "smtp.gmail.com"
smtp_port = 587
sender_email = "your-email@gmail.com"
sender_password = "your-app-specific-password"

# Optional: Google Cloud Storage (if using GCP)
[gcp]
project_id = "your-project-id"
bucket_name = "your-bucket-name"
credentials_path = "path/to/credentials.json" 